include: package:lint/strict.yaml
# Lint rules to be applied
linter:
  rules:
    avoid_classes_with_only_static_members: false
# Style guide settings
style:
  # Enforce the maximum line length.
  line_length: 100
  # Use a consistent indentation.
  indent: 2
  # Enforce curly braces for all control flow statements.
  require_curly_braces: true
  # Enforce using double quotes for strings.
  prefer_double_quotes: true
  # Use this to specify the order of import directives.
  # For example, if you want all 'dart:' imports first followed by 'package:' imports.
  # Otherwise, you can remove this setting if import order is not important to you.
  import_order:
    - "dart"
    - "package"

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
