targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # this for @RoutePage
        generate_for:
          - lib/modules/**_screen.dart
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        generate_for:
          - lib/core/routes/app_router.dart
      json_serializable:
        generate_for:
          - lib/core/data/models/**.dart
        options:
          checked: true
