name: flutter_project_boilerplate
description: Flutter Boilerplate
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.7.1
  dio: ^5.3.0
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  auto_route_generator: ^7.2.0
  build_config: ^1.1.1
  build_runner: ^2.4.6
  flutter_flavorizr: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.0.0
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.staging
    - .env.dev
    - assets/
    - assets/translations/

scripts: derry.yaml
